development:
  adapter: postgresql
  encoding: utf8
  database: project_development
  host: localhost
  pool: 5
  username: rubypg
  password: rubypg

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: project_test
  host: localhost
  pool: 5
  username: rubypg
  password: rubypg

production:
  url: <%= ENV['DATABASE_URL'] %>

cucumber:
  <<: *TEST
